server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Horizones/test-springcloud.git
          search-paths: config
          username: 3153852619@qq.com
          password: 123dxlhahaha
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/